name: Vite and Cypress CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install  

      - name: Build with Vite (assuming build command is 'build')
        run: npm run build  

      - name: Start Vite server in background
        run: npm run dev &  
        env:
          CI: true  

      - name: Wait for Vite server to start
        run: npx wait-on http://localhost:5173

      - name: Run Cypress tests
        run: npm run test:ci 
        env:
          CYPRESS_BASE_URL: http://localhost:5173  
